export type PosterGameMovie = {
  title: string;
  poster_path: string;
  aliases?: string[];
};

// Curated list of globally recognizable films with strong poster iconography.
// poster_path values resolved via TMDB /search/movie lookups (real TMDB assets).
export const POSTER_GAME_MOVIES: PosterGameMovie[] = [
  { title: 'The Godfather', poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg' },
  { title: 'Pulp Fiction', poster_path: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg' },
  { title: 'The Dark Knight', poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', aliases: ['dark knight'] },
  { title: 'Inception', poster_path: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg' },
  { title: 'Titanic', poster_path: '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg' },
  { title: 'Jaws', poster_path: '/lxM6kqilAdpdhqUl2biYp5frUxE.jpg' },
  { title: 'The Matrix', poster_path: '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg', aliases: ['matrix'] },
  { title: 'Fight Club', poster_path: '/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg' },
  { title: 'The Shawshank Redemption', poster_path: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', aliases: ['shawshank redemption', 'shawshank'] },
  { title: 'Star Wars', poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', aliases: ['star wars episode iv', 'a new hope'] },
  { title: 'Jurassic Park', poster_path: '/63viWuPfYQjRYLSZSZNq7dglJP5.jpg' },
  { title: 'The Lion King', poster_path: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', aliases: ['lion king'] },
  { title: 'Back to the Future', poster_path: '/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg' },
  { title: 'Alien', poster_path: '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg' },
  { title: 'E.T. the Extra-Terrestrial', poster_path: '/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg', aliases: ['et', 'e.t.', 'the extra-terrestrial'] },
  { title: 'The Silence of the Lambs', poster_path: '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg', aliases: ['silence of the lambs'] },
  { title: 'Gladiator', poster_path: '/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg' },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', aliases: ['fellowship of the ring', 'lord of the rings', 'lotr'] },
  { title: 'Psycho', poster_path: '/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg' },
  { title: 'Parasite', poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg' },
  { title: 'Whiplash', poster_path: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg' },
  { title: 'La La Land', poster_path: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg' },
  { title: 'Get Out', poster_path: '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg' },
  { title: 'Interstellar', poster_path: '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg' },
  { title: 'Spirited Away', poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg' },
  { title: 'Joker', poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg' },
  { title: 'Django Unchained', poster_path: '/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg', aliases: ['django'] },
  { title: 'Amélie', poster_path: '/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg', aliases: ['amelie'] },
  { title: 'The Grand Budapest Hotel', poster_path: '/zOVCqKUzjFKqa1eDMcOzvXwthY4.jpg', aliases: ['grand budapest hotel'] },
];

// Title-only entries with no verified poster asset. These exist purely to make the
// typeahead dropdown feel richer and are never drawn as an actual game round
// (see drawShuffledMovie in LetterboxdLanding.tsx, which only reads POSTER_GAME_MOVIES).
export const SUGGESTION_ONLY_TITLES: string[] = [
  'Forrest Gump',
  'The Avengers',
  'Avatar',
  'Batman Begins',
  'Iron Man',
  'Spider-Man',
  'The Departed',
  'Goodfellas',
  'Casablanca',
  "Schindler's List",
  'Saving Private Ryan',
  'The Green Mile',
  'Se7en',
  'The Usual Suspects',
  'American Beauty',
  'No Country for Old Men',
  'There Will Be Blood',
  'Once Upon a Time in Hollywood',
  'Kill Bill',
  'Reservoir Dogs',
  'Inglourious Basterds',
  'The Prestige',
  'Memento',
  'Dunkirk',
  'The Wolf of Wall Street',
  'Catch Me If You Can',
  'Gone Girl',
  'Zodiac',
  'Arrival',
  'Blade Runner',
  'Mad Max: Fury Road',
  'The Terminator',
  'Aliens',
  'Predator',
  'Die Hard',
  'Rocky',
  'Braveheart',
  '12 Years a Slave',
  'Moonlight',
  'The Shape of Water',
  'Birdman',
  'Black Swan',
  'Requiem for a Dream',
  'American History X',
  'Fargo',
  'The Big Lebowski',
  'Casino',
  'Scarface',
  'Heat',
  'Léon: The Professional',
  'City of God',
  'Oldboy',
  'Your Name',
  'Princess Mononoke',
  "Howl's Moving Castle",
  'Toy Story',
  'Finding Nemo',
  'Up',
  'WALL-E',
  'Coco',
  'Inside Out',
  'Ratatouille',
  'Shrek',
  'The Incredibles',
  'Frozen',
  'Moana',
  'Zootopia',
  'Coraline',
  "Pan's Labyrinth",
  'Amadeus',
  'Apocalypse Now',
];
