export type PosterGameMovie = {
  title: string;
  poster_path: string;
  aliases?: string[];
};

// Curated list of globally recognizable films with strong poster iconography.
// poster_path values resolved via TMDB /search/movie lookups (real TMDB assets).
export const POSTER_GAME_MOVIES: PosterGameMovie[] = [
  { title: 'The Godfather', poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg' },
  { title: 'Pulp Fiction', poster_path: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg' },
  { title: 'The Dark Knight', poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', aliases: ['dark knight'] },
  { title: 'Inception', poster_path: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg' },
  { title: 'Titanic', poster_path: '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg' },
  { title: 'Jaws', poster_path: '/lxM6kqilAdpdhqUl2biYp5frUxE.jpg' },
  { title: 'The Matrix', poster_path: '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg', aliases: ['matrix'] },
  { title: 'Fight Club', poster_path: '/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg' },
  { title: 'The Shawshank Redemption', poster_path: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', aliases: ['shawshank redemption', 'shawshank'] },
  { title: 'Star Wars', poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', aliases: ['star wars episode iv', 'a new hope'] },
  { title: 'Jurassic Park', poster_path: '/63viWuPfYQjRYLSZSZNq7dglJP5.jpg' },
  { title: 'The Lion King', poster_path: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', aliases: ['lion king'] },
  { title: 'Back to the Future', poster_path: '/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg' },
  { title: 'Alien', poster_path: '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg' },
  { title: 'E.T. the Extra-Terrestrial', poster_path: '/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg', aliases: ['et', 'e.t.', 'the extra-terrestrial'] },
  { title: 'The Silence of the Lambs', poster_path: '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg', aliases: ['silence of the lambs'] },
  { title: 'Gladiator', poster_path: '/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg' },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', aliases: ['fellowship of the ring', 'lord of the rings', 'lotr'] },
  { title: 'Psycho', poster_path: '/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg' },
  { title: 'Parasite', poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg' },
  { title: 'Whiplash', poster_path: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg' },
  { title: 'La La Land', poster_path: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg' },
  { title: 'Get Out', poster_path: '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg' },
  { title: 'Interstellar', poster_path: '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg' },
  { title: 'Spirited Away', poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg' },
  { title: 'Joker', poster_path: '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg' },
  { title: 'Django Unchained', poster_path: '/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg', aliases: ['django'] },
  { title: 'Amélie', poster_path: '/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg', aliases: ['amelie'] },
  { title: 'The Grand Budapest Hotel', poster_path: '/zOVCqKUzjFKqa1eDMcOzvXwthY4.jpg', aliases: ['grand budapest hotel'] },
  { title: 'Forrest Gump', poster_path: '/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg' },
  { title: 'The Avengers', poster_path: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg' },
  { title: 'Avatar', poster_path: '/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg' },
  { title: 'Batman Begins', poster_path: '/sPX89Td70IDDjVr85jdSBb4rWGr.jpg' },
  { title: 'Iron Man', poster_path: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg' },
  { title: 'Spider-Man', poster_path: '/kjdJntyBeEvqm9w97QGBdxPptzj.jpg' },
  { title: 'The Departed', poster_path: '/nT97ifVT2J1yMQmeq20Qblg61T.jpg' },
  { title: 'Goodfellas', poster_path: '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg' },
  { title: 'Casablanca', poster_path: '/lGCEKlJo2CnWydQj7aamY7s1S7Q.jpg' },
  { title: "Schindler's List", poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg' },
  { title: 'Saving Private Ryan', poster_path: '/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg' },
  { title: 'The Green Mile', poster_path: '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg' },
  { title: 'Se7en', poster_path: '/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg' },
  { title: 'The Usual Suspects', poster_path: '/99X2SgyFunJFXGAYnDv3sb9pnUD.jpg' },
  { title: 'American Beauty', poster_path: '/wby9315QzVKdW9BonAefg8jGTTb.jpg' },
  { title: 'No Country for Old Men', poster_path: '/uB7RDZby43Wvu8SKGHHTwGyTDBX.jpg' },
  { title: 'There Will Be Blood', poster_path: '/fa0RDkAlCec0STeMNAhPaF89q6U.jpg' },
  { title: 'Once Upon a Time in Hollywood', poster_path: '/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg' },
  { title: 'Kill Bill', poster_path: '/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg' },
  { title: 'Reservoir Dogs', poster_path: '/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg' },
  { title: 'Inglourious Basterds', poster_path: '/aupnPtagH9JVBuMrGEanf4iqXEQ.jpg' },
  { title: 'The Prestige', poster_path: '/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg' },
  { title: 'Memento', poster_path: '/fKTPH2WvH8nHTXeBYBVhawtRqtR.jpg' },
  { title: 'Dunkirk', poster_path: '/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg' },
  { title: 'The Wolf of Wall Street', poster_path: '/kW9LmvYHAaS9iA0tHmZVq8hQYoq.jpg' },
  { title: 'Catch Me If You Can', poster_path: '/ctjEj2xM32OvBXCq8zAdK3ZrsAj.jpg' },
  { title: 'Gone Girl', poster_path: '/ts996lKsxvjkO2yiYG0ht4qAicO.jpg' },
  { title: 'Zodiac', poster_path: '/6YmeO4pB7XTh8P8F960O1uA14JO.jpg' },
  { title: 'Arrival', poster_path: '/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg' },
  { title: 'Blade Runner', poster_path: '/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg' },
  { title: 'Mad Max: Fury Road', poster_path: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg' },
  { title: 'The Terminator', poster_path: '/qvktm0BHcnmDpul4Hz01GIazWPr.jpg' },
  { title: 'Aliens', poster_path: '/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg' },
  { title: 'Predator', poster_path: '/aN3cdjIK70KGmD84et8MMblU87Q.jpg' },
  { title: 'Die Hard', poster_path: '/7Bjd8kfmDSOzpmhySpEhkUyK2oH.jpg' },
  { title: 'Rocky', poster_path: '/aYtBYWqCdUqcnoodWJdcTG3pFev.jpg' },
  { title: 'Braveheart', poster_path: '/or1gBugydmjToAEq7OZY0owwFk.jpg' },
  { title: '12 Years a Slave', poster_path: '/xdANQijuNrJaw1HA61rDccME4Tm.jpg' },
  { title: 'Moonlight', poster_path: '/qLnfEmPrDjJfPyyddLJPkXmshkp.jpg' },
  { title: 'The Shape of Water', poster_path: '/9zfwPffUXpBrEP26yp0q1ckXDcj.jpg' },
  { title: 'Birdman', poster_path: '/9n0u3Ee7OUjgeyF5kIwahxkf4xm.jpg' },
  { title: 'Black Swan', poster_path: '/viWheBd44bouiLCHgNMvahLThqx.jpg' },
  { title: 'Requiem for a Dream', poster_path: '/9BTwsLaMVHOGFlmsSlx5QYCaXb.jpg' },
  { title: 'American History X', poster_path: '/x2drgoXYZ8484lqyDj7L1CEVR4T.jpg' },
  { title: 'Fargo', poster_path: '/rt7cpEr1uP6RTZykBFhBTcRaKvG.jpg' },
  { title: 'The Big Lebowski', poster_path: '/3bv6WAp6BSxxYvB5ozKFUYuRA8C.jpg' },
  { title: 'Casino', poster_path: '/gziIkUSnYuj9ChCi8qOu2ZunpSC.jpg' },
  { title: 'Scarface', poster_path: '/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg' },
  { title: 'Heat', poster_path: '/e09dLw1Ljtccd2P4NsuUvVtS5du.jpg' },
  { title: 'Léon: The Professional', poster_path: '/bxB2q91nKYp8JNzqE7t7TWBVupB.jpg', aliases: ['leon', 'leon the professional'] },
  { title: 'City of God', poster_path: '/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg' },
  { title: 'Oldboy', poster_path: '/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg' },
  { title: 'Your Name', poster_path: '/bXE0gPdWpQIfG5GbiqqYxt7MkZJ.jpg' },
  { title: 'Princess Mononoke', poster_path: '/cMYCDADoLKLbB83g4WnJegaZimC.jpg' },
  { title: "Howl's Moving Castle", poster_path: '/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg' },
  { title: 'Toy Story', poster_path: '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg' },
  { title: 'Finding Nemo', poster_path: '/5lc6nQc0VhWFYFbNv016xze8Jvy.jpg' },
  { title: 'Up', poster_path: '/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg' },
  { title: 'WALL-E', poster_path: '/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg' },
  { title: 'Coco', poster_path: '/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg' },
  { title: 'Inside Out', poster_path: '/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg' },
  { title: 'Ratatouille', poster_path: '/t3vaWRPSf6WjDSamIkKDs1iQWna.jpg' },
  { title: 'Shrek', poster_path: '/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg' },
  { title: 'The Incredibles', poster_path: '/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg' },
  { title: 'Frozen', poster_path: '/itAKcobTYGpYT8Phwjd8c9hleTo.jpg' },
  { title: 'Moana', poster_path: '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg' },
  { title: 'Zootopia', poster_path: '/hlK0e0wAQ3VLuJcsfIYPvb4JVud.jpg' },
  { title: 'Coraline', poster_path: '/4jeFXQYytChdZYE9JYO7Un87IlW.jpg' },
  { title: "Pan's Labyrinth", poster_path: '/z7xXihu5wHuSMWymq5VAulPVuvg.jpg' },
  { title: 'Amadeus', poster_path: '/gQRfiyfGvr1az0quaYyMram3Aqt.jpg' },
  { title: 'Apocalypse Now', poster_path: '/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg' },
];

// Title-only entries with no verified poster asset. These exist purely to make the
// typeahead dropdown feel richer and are never drawn as an actual game round
// (see drawShuffledMovie in LetterboxdLanding.tsx, which only reads POSTER_GAME_MOVIES).
export const SUGGESTION_ONLY_TITLES: string[] = [];
