export type PosterGameMovie = {
  title: string;
  poster_path: string;
  aliases?: string[];
};

// IMDb Top 100 Narrative Feature Films (list ls082915895), in list order.
// poster_path values resolved via TMDB /search/movie lookups (real TMDB assets).
export const POSTER_GAME_MOVIES: PosterGameMovie[] = [
  { title: 'The Shawshank Redemption', poster_path: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', aliases: ['shawshank redemption', 'shawshank'] },
  { title: 'The Godfather', poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg' },
  { title: 'The Godfather Part II', poster_path: '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', aliases: ['godfather part 2', 'godfather 2'] },
  { title: 'The Dark Knight', poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', aliases: ['dark knight'] },
  { title: '12 Angry Men', poster_path: '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg' },
  { title: "Schindler's List", poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg' },
  { title: 'The Lord of the Rings: The Return of the King', poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', aliases: ['return of the king', 'lord of the rings', 'lotr'] },
  { title: 'Pulp Fiction', poster_path: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg' },
  { title: 'The Good, the Bad and the Ugly', poster_path: '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', aliases: ['il buono il brutto il cattivo', 'good the bad and the ugly'] },
  { title: 'Fight Club', poster_path: '/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg' },
  { title: 'The Lord of the Rings: The Fellowship of the Ring', poster_path: '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', aliases: ['fellowship of the ring', 'lord of the rings', 'lotr'] },
  { title: 'Forrest Gump', poster_path: '/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg' },
  { title: 'Inception', poster_path: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg' },
  { title: 'Star Wars: Episode V - The Empire Strikes Back', poster_path: '/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg', aliases: ['empire strikes back', 'star wars episode 5'] },
  { title: 'The Lord of the Rings: The Two Towers', poster_path: '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg', aliases: ['two towers', 'lord of the rings', 'lotr'] },
  { title: "One Flew Over the Cuckoo's Nest", poster_path: '/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg', aliases: ['cuckoos nest'] },
  { title: 'GoodFellas', poster_path: '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg', aliases: ['goodfellas'] },
  { title: 'The Matrix', poster_path: '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg', aliases: ['matrix'] },
  { title: 'Star Wars', poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', aliases: ['star wars episode iv', 'a new hope'] },
  { title: 'Seven Samurai', poster_path: '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg', aliases: ['shichinin no samurai'] },
  { title: 'Se7en', poster_path: '/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg', aliases: ['seven', 'se7en'] },
  { title: 'City of God', poster_path: '/k7eYdWvhYQyRQoU2TB2A2Xu2TfD.jpg', aliases: ['cidade de deus'] },
  { title: "It's a Wonderful Life", poster_path: '/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg', aliases: ['wonderful life'] },
  { title: 'The Silence of the Lambs', poster_path: '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg', aliases: ['silence of the lambs'] },
  { title: 'The Usual Suspects', poster_path: '/99X2SgyFunJFXGAYnDv3sb9pnUD.jpg', aliases: ['usual suspects'] },
  { title: 'Saving Private Ryan', poster_path: '/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg' },
  { title: 'Aliens', poster_path: '/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg' },
  { title: 'Interstellar', poster_path: '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg' },
  { title: 'The Bourne Ultimatum', poster_path: '/15rMz5MRXFp7CP4VxhjYw4y0FUn.jpg', aliases: ['bourne ultimatum'] },
  { title: 'The Green Mile', poster_path: '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg', aliases: ['green mile'] },
  { title: 'American History X', poster_path: '/x2drgoXYZ8484lqyDj7L1CEVR4T.jpg' },
  { title: 'Psycho', poster_path: '/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg' },
  { title: 'Fargo', poster_path: '/rt7cpEr1uP6RTZykBFhBTcRaKvG.jpg' },
  { title: 'Casablanca', poster_path: '/lGCEKlJo2CnWydQj7aamY7s1S7Q.jpg' },
  { title: 'The Pianist', poster_path: '/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg', aliases: ['pianist'] },
  { title: 'The Departed', poster_path: '/nT97ifVT2J1yMQmeq20Qblg61T.jpg', aliases: ['departed'] },
  { title: 'Back to the Future', poster_path: '/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg' },
  { title: 'Terminator 2: Judgment Day', poster_path: '/jFTVD4XoWQTcg7wdyJKa8PEds5q.jpg', aliases: ['terminator 2', 't2'] },
  { title: 'Whiplash', poster_path: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg' },
  { title: 'Rear Window', poster_path: '/ILVF0eJxHMddjxeQhswFtpMtqx.jpg' },
  { title: 'The Lion King', poster_path: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', aliases: ['lion king'] },
  { title: 'Gladiator', poster_path: '/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg' },
  { title: 'Raiders of the Lost Ark', poster_path: '/ceG9VzoRAVGwivFU403Wc3AHRys.jpg', aliases: ['indiana jones'] },
  { title: 'The Prestige', poster_path: '/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg', aliases: ['prestige'] },
  { title: 'Platoon', poster_path: '/m3mmFkPQKvPZq5exmh0bDuXlD9T.jpg' },
  { title: 'Apocalypse Now', poster_path: '/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg' },
  { title: 'Memento', poster_path: '/fKTPH2WvH8nHTXeBYBVhawtRqtR.jpg' },
  { title: 'Alien', poster_path: '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg' },
  { title: 'Sunset Boulevard', poster_path: '/zt8aQ6ksqK6p1AopC5zVTDS9pKT.jpg', aliases: ['sunset blvd'] },
  { title: 'Dr. Strangelove', poster_path: '/6x7MzQ6BOMlRzam1StcmPO9v61g.jpg', aliases: ['dr strangelove', 'how i learned to stop worrying and love the bomb'] },
  { title: 'Django Unchained', poster_path: '/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg', aliases: ['django'] },
  { title: 'Argo', poster_path: '/m5gPWFZFIp4UJFABgWyLkbXv8GX.jpg' },
  { title: 'WALL·E', poster_path: '/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg', aliases: ['walle', 'wall-e'] },
  { title: 'The Dark Knight Rises', poster_path: '/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg', aliases: ['dark knight rises'] },
  { title: 'The English Patient', poster_path: '/8eHHqMg8qEYtVw8LQLygsHXSR2q.jpg', aliases: ['english patient'] },
  { title: 'American Beauty', poster_path: '/wby9315QzVKdW9BonAefg8jGTTb.jpg' },
  { title: 'Citizen Kane', poster_path: '/sav0jxhqiH0bPr2vZFU0Kjt2nZL.jpg' },
  { title: 'Braveheart', poster_path: '/or1gBugydmjToAEq7OZY0owwFk.jpg' },
  { title: 'Vertigo', poster_path: '/15uOEfqBNTVtDUT7hGBVCka0rZz.jpg' },
  { title: 'Star Wars: Episode VI - Return of the Jedi', poster_path: '/jQYlydvHm3kUix1f8prMucrplhm.jpg', aliases: ['return of the jedi', 'star wars episode 6'] },
  { title: 'Reservoir Dogs', poster_path: '/xi8Iu6qyTfyZVDVy60raIOYJJmk.jpg' },
  { title: 'Amadeus', poster_path: '/gQRfiyfGvr1az0quaYyMram3Aqt.jpg' },
  { title: 'Dunkirk', poster_path: '/b4Oe15CGLL61Ped0RAS9JpqdmCt.jpg' },
  { title: "Singin' in the Rain", poster_path: '/w03EiJVHP8Un77boQeE7hg9DVdU.jpg', aliases: ['singing in the rain'] },
  { title: 'Eternal Sunshine of the Spotless Mind', poster_path: '/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg', aliases: ['eternal sunshine'] },
  { title: 'A Clockwork Orange', poster_path: '/4sHeTAp65WrSSuc05nRBKddhBxO.jpg', aliases: ['clockwork orange'] },
  { title: '2001: A Space Odyssey', poster_path: '/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg', aliases: ['space odyssey'] },
  { title: 'Toy Story', poster_path: '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg' },
  { title: 'To Kill a Mockingbird', poster_path: '/gZycFUMLx2110dzK3nBNai7gfpM.jpg', aliases: ['mockingbird'] },
  { title: 'Taxi Driver', poster_path: '/ekstpH614fwDX8DUln1a2Opz0N8.jpg' },
  { title: 'Inglourious Basterds', poster_path: '/aupnPtagH9JVBuMrGEanf4iqXEQ.jpg' },
  { title: '12 Years a Slave', poster_path: '/xdANQijuNrJaw1HA61rDccME4Tm.jpg' },
  { title: 'Good Will Hunting', poster_path: '/z2FnLKpFi1HPO7BEJxdkv6hpJSU.jpg' },
  { title: 'Snatch', poster_path: '/kJZoAHq1SLDdWjeNGtlHAnGpmFV.jpg' },
  { title: 'V for Vendetta', poster_path: '/1avD1JeaRiJX5M4ahPdZPypGoGN.jpg' },
  { title: 'L.A. Confidential', poster_path: '/lWCgf5sD5FpMljjpkRhcC8pXcch.jpg', aliases: ['la confidential'] },
  { title: 'Up', poster_path: '/mFvoEwSfLqbcWwFsDjQebn9bzFe.jpg' },
  { title: 'The Aviator', poster_path: '/lx4kWcZc3o9PaNxlQpEJZM17XUI.jpg', aliases: ['aviator'] },
  { title: 'Avatar', poster_path: '/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg' },
  { title: 'Titanic', poster_path: '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg' },
  { title: 'Jaws', poster_path: '/lxM6kqilAdpdhqUl2biYp5frUxE.jpg' },
  { title: 'Jurassic Park', poster_path: '/63viWuPfYQjRYLSZSZNq7dglJP5.jpg' },
  { title: 'Die Hard', poster_path: '/7Bjd8kfmDSOzpmhySpEhkUyK2oH.jpg' },
  { title: 'Rocky', poster_path: '/aYtBYWqCdUqcnoodWJdcTG3pFev.jpg' },
  { title: 'E.T. the Extra-Terrestrial', poster_path: '/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg', aliases: ['et', 'e.t.', 'the extra-terrestrial'] },
  { title: 'No Country for Old Men', poster_path: '/uB7RDZby43Wvu8SKGHHTwGyTDBX.jpg' },
  { title: 'Kill Bill: Vol. 1', poster_path: '/v7TaX8kXMXs5yFFGR41guUDNcnB.jpg', aliases: ['kill bill vol 1', 'kill bill'] },
  { title: 'Kill Bill: Vol. 2', poster_path: '/2yhg0mZQMhDyvUQ4rG1IZ4oIA8L.jpg', aliases: ['kill bill vol 2'] },
  { title: 'Rain Man', poster_path: '/iTNHwO896WKkaoPtpMMS74d8VNi.jpg' },
  { title: 'Birdman or (The Unexpected Virtue of Ignorance)', poster_path: '/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg', aliases: ['birdman'] },
  { title: 'Mad Max: Fury Road', poster_path: '/hA2ple9q4qnwxp3hKVNhroipsir.jpg' },
  { title: 'Raging Bull', poster_path: '/1WV7WlTS8LI1L5NkCgjWT9GSW3O.jpg' },
  { title: "The King's Speech", poster_path: '/pVNKXVQFukBaCz6ML7GH3kiPlQP.jpg', aliases: ['kings speech'] },
  { title: 'There Will Be Blood', poster_path: '/fa0RDkAlCec0STeMNAhPaF89q6U.jpg' },
  { title: 'Gone with the Wind', poster_path: '/lNz2Ow0wGCAvzckW7EOjE03KcYv.jpg' },
  { title: 'Dallas Buyers Club', poster_path: '/7Fdh7gUq3plvQqxRbNYhWvDABXA.jpg' },
  { title: 'Chinatown', poster_path: '/kZRSP3FmOcq0xnBulqpUQngJUXY.jpg' },
  { title: 'Ben-Hur', poster_path: '/m4WQ1dBIrEIHZNCoAjdpxwSKWyH.jpg', aliases: ['ben hur'] },
  { title: 'Gandhi', poster_path: '/rOXftt7SluxskrFrvU7qFJa5zeN.jpg' },
  { title: 'The French Connection', poster_path: '/pH4saPwMjhnVGwmSH6RkMaHrt3s.jpg', aliases: ['french connection'] },
];

// Title-only entries with no verified poster asset. These exist purely to make the
// typeahead dropdown feel richer and are never drawn as an actual game round
// (see drawShuffledMovie in LetterboxdLanding.tsx, which only reads POSTER_GAME_MOVIES).
export const SUGGESTION_ONLY_TITLES: string[] = [];
